### ISSUE TITLE
Allow RFC Compliant AD / LDS DN Renames

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/transform-engine#1]
As per http://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx

Another article: https://msdn.microsoft.com/en-us/library/aa366101(v=vs.85).aspx

Can we create a transform which does a \ escape for characters mentioned above?

**Comment by ryannewington** [comment]
Fixed in ACMA https://github.com/lithnet/acma/releases/tag/v1.1.6258
Fixed in UMARE https://github.com/lithnet/umare/releases/tag/v1.5.6258
