### ISSUE TITLE
Enhancement: Add regex match/notmatch operator to Multivalued-to-single-valued transform

### ISSUE THREAD

**Issue by Froosh** [lithnet/transform-engine#3]
Being able to filter multi-values in/out by arbitrary regex would be awesome 😁

**Comment by ryannewington** [comment]
In UMARE or ACMA?

**Comment by Froosh** [comment]
I was starting from UMARE, but since the documentation links straight to the transform library, seemed best to log it here...

**Comment by ryannewington** [comment]
Yep right place, just wanted to make sure I got updated the product you wanted first.

**Comment by ryannewington** [comment]
I'm having trouble with my signing certificate, and I'm not sure I have the patience to fight with it tonight, but here is an unsigned build to test with in the mean time [Lithnet.Umare.msi.zip](https://github.com/lithnet/transform-engine/files/1332445/Lithnet.Umare.msi.zip)

**Comment by Froosh** [comment]
Heh, I broke my test lab, so I may not get to it tonight either. Seriously though, too awesome for words, thanks!

**Comment by ryannewington** [comment]
how did you go with this @Froosh? did you get a chance to test and see if it met your needs?

**Comment by Froosh** [comment]
Apologies, yes, this was perfect!

**Comment by ryannewington** [comment]
Release build is up
https://github.com/lithnet/umare/releases/tag/v1.5.6488
