### ISSUE TITLE
Transform tester caches first loaded PowerShell script

### ISSUE THREAD

**Issue by ryannewington** [lithnet/transform-engine#5]

**Comment by ryannewington** [comment]
I've found this across a few transforms @froosh

**Comment by Froosh** [comment]
I'm finding it with C# transforms as well

Edit: ah, and I see you've adjusted that :D

**Comment by ryannewington** [comment]
Yep

src/Lithnet.Transforms/Transforms/CSharpScriptTransform.cs
src/Lithnet.Transforms/Transforms/DelimitedTextFileLookupTransform.cs
src/Lithnet.Transforms/Transforms/PowerShellScriptTransform.cs
src/Lithnet.Transforms/Transforms/XmlLookupTransform.cs

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/umare/releases/tag/v1.5.6591
